shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379
#yzpnb:
#  jwt:
#    # 加密秘钥
#    secret: f4e2e52034348f86b67cde581c0f9eb5
#    # token有效时长,1天,单位秒
#    expire: 86400
#    header: token
